### ISSUE TITLE
Error when running yarn serve.

### ISSUE THREAD

**Issue by cxoltero** [kenzanlabs/angular-webpack-stack#15]
when on brach [ enhancement/issues#5-develop-reference-app ](https://github.com/kenzanlabs/angular-webpack-stack/tree/enhancement/issues%235-develop-reference-app)
run ```yarn run serve ```
error: ``` Uncaught Error: Template parse errors:
Unexpected closing tag "a". ```

this is refering to an unclosed link tag. All of the tags are closed. and the error does not happen in when running ```yarn run develop```.

Also, making sure that the expected behavior for http call will be to make it using observables.

**Comment by thescientist13** [comment]
My guess is that is a byproduct of the `build` task specifically.  That said, I tried both on that branch and did not get that error using `build` or `serve`.   

It's hard to tell if this is browser error, webpack build error, or something else so not sure specifically where to continue debugging on this.  I would try deleting _node_modules_, running `yarn install` and trying again.

That said, running `serve` just loaded a white page for me with no meaningful console errors / message, FYI.  
<img width="890" alt="screen shot 2017-08-09 at 6 09 06 pm" src="https://user-images.githubusercontent.com/895923/29146176-e3bd3018-7d2d-11e7-88dd-34d7ee2dd496.png">

**Comment by cxoltero** [comment]
after deleting and reinstalling node modules and, clearing cache. error still present.

<img width="824" alt="screen shot 2017-08-09 at 7 30 41 pm" src="https://user-images.githubusercontent.com/7050734/29148103-6accd3dc-7d39-11e7-9939-3cc29e7a3045.png">
<img width="836" alt="screen shot 2017-08-09 at 7 30 33 pm" src="https://user-images.githubusercontent.com/7050734/29148109-74375230-7d39-11e7-87bd-2ceb11bcf4d0.png">

**Comment by thescientist13** [comment]
Ah, ok so this is a console error.

I'm still only seeing a white page, will see if someone else can test and report back.

**Comment by thescientist13** [comment]
@cxoltero 
I can reproduce now, just had my brower's logging levels messed up.  I will take a look into this if you want to continue with the principal task of building the reference app.

One thought I had is that in my repo, I had this in prod webpack config but at this time I can't remember why I had it there
https://github.com/thegreenhouseio/angular-webapp-seed/blob/master/webpack.config.prod.js#L45

I would try that out to see if it helps, and then see we can can find a resource that explains why it fixes it.

**Comment by paul-barry-kenzan** [comment]
@cxoltero @thescientist13 
Followed the steps suggested, and am seeing the same error in the console.

**Comment by paul-barry-kenzan** [comment]
Some additional info. 

I decided to comment out the lines being identified in the console errors. Each time it complained about an `<a>`, I commented it out. THEN, I got a new error (screenshot below). 

<img width="1435" alt="screen shot 2017-08-10 at 12 12 54 pm" src="https://user-images.githubusercontent.com/12274057/29180304-65c76f0a-7dc5-11e7-9bdb-5f0d49083a1b.png">

Commenting out the `<contact-list>` within `home.html`, I received yet another error (screenshot below)

<img width="1428" alt="screen shot 2017-08-10 at 12 20 02 pm" src="https://user-images.githubusercontent.com/12274057/29180630-5e303992-7dc6-11e7-8410-237c9701ac05.png">

That's where I've left off since it's starting to get deep. Hope this helps.

**Comment by thescientist13** [comment]
awesome, thanks @paul-barry-kenzan !

**Comment by cxoltero** [comment]
It seems like a few people are having the same error. 

Current Fix: 
add [workaround](https://github.com/AngularClass/angular-starter/blob/master/config/webpack.prod.js#L300) for angular 2 html syntax
```
   // it seems like some angular 
    new webpack.LoaderOptionsPlugin({
      options: {
        htmlLoader: {
          minimize: false
        }
      }
    })
```

**Comment by thescientist13** [comment]
ok, let's include that in the config and the links.  ideally would be great to track that down to a github link or SO post or something.  I will keep this issue open to try and find that.
