### ISSUE TITLE
HMR removes clickable behavior from buttons

### ISSUE THREAD

**Issue by cxoltero** [kenzanlabs/angular-webpack-stack#35]
## Steps to reproduce:
1. run  `yarn run develop`
1. navigate to http://localhost:9000/
1. add two contacts
1. make a code change case 'background-color'

## expected behavior.
 1. when user clicks on either contact button, the contact information component gets updated.

## actual behavior.
 1. contact buttons do not show clickable behavior.

**Comment by thescientist13** [comment]
Thanks @cxoltero !

As the HMR PR will not be actually merged, I will close this, but reference it in the PR we keep open as a standing reference to implementing HMR
